#+SETUPFILE: ../../template/level2.org

#+TITLE: Orgnize my life by org-mode
* What is Org mode
+ [[http://orgmode.org/][Org mode]] is a major mode in Emacs and it is designed for keeping nodes, maitaining TODO lists. And it is also used for authoring documents. 
+ Org mode keep everything in a plain text format so it is really fast and effective to maintain. 
* How I use Org mode 
+ I'm using Org mode for differents purposes:
  1. Keeping todo list for both my work and family.
  2. Record the time for my working tasks.
  3. Weekly review and daily review. 
  4. Maintain my personal blog.
+ To achieve these goals I need to correct configurate my Emacs. My Emacs configurations are in github [[https://github.com/felixyao/dotemacs][dotemacs]]. you can fetch them by git commands:
#+BEGIN_SRC bash
git clone git://github.com/felixyao/dotemacs.git
#+END_SRC
Another very good example to use org mode [[http://doc.norang.ca/org-mode.html][Org Mode - Organize Your Life In Plain Text!]]
* Create Tasks
** Org files used for keeping todo list
Here is the org files I'm using for keep all my todo list
| filename  | Todos                     |
| work.org  | tasks releated to my work |
| todo.org  | personal tasks            |
| dairy.org | record some time[fn:1]    |
The first Heading is the category of tasks here is a example of my todo.org:
#+BEGIN_EXAMPLE
 * Special Datas
 * Finaces
 * Tasks
 ...
#+END_EXAMPLE
Usually I don't check the task in the files, and during [[*Weekly%20review][Weekly review]] I will go though the files to make sure 
All tasks are belongs to the suit category.
** Create Tasks During weekly review
During [[*Weekly review][Weekly review]] I go through todo.org and work.org files to catch the ideas which in my mind to put them into my GTD system.
** Capture a idea
Org capture mode is a great tool to catch the idea comes to my mind in a sudden. when a idea comes I type a command to echo 
a capture menu, and choose a task type. Then Emacs will lanuch a caputre buffer for me to edit the task. after that I can 
type a command to record the task to the right place in my org files.
+ Commands to echo the capture menu:
#+BEGIN_SRC bash
C-c c
#+END_SRC

+ Commands to choose task template in capture menu:

| command | Todo                                                                 |
| t       | Create a personal task and put into todo.org/Tasks                   |
| w       | Create a working task and put into work.org/Tasks                    |
| i       | Create a Interuption task [fn:2] and put into work.org/Interruptions |
| m       | Create a task for meeting work.org/meetings                          |
| j       | Create a janural record what i have done [fn:3] into dairy.org |

+ Commands to record the captured task:

| command |                                                               |
| C-c C-c | Store the task to the default place according to the template |
| C-c C-k | Delete the captured task                                      |
| C-c C-w | Store the task and choose a place                             |
  
* Following the todo list
** The agenda view 
I customnize a agenda view as my todo list. The agenda view include four parts. the first one is the agenda for today it shows the tasks I have to be done today in 
specific time, the sceond is the tasks that need to be planned.  after that is a task list I have to do recently but not necessary to be done today. the followed part
is the tasks that I have delegated to someone else. last part is the tasks I have done 2 weeks ago.
The agenda view is echoed by the command:
#+BEGIN_EXAMPLE
C-c a space
#+END_EXAMPLE
In principle, I choose a task to do by go through the agenda view from top to button.
First I finished the tasks have been scheduled. then I start to plan the tasks have been planed. Planning a task usually I don't take care how to do it but just 
decide is the task could be done right now(schedule it or put it into todo list): is the task is too complicate and better make more steps for it(Create a [[*Organize%20a%20project][Project]]):
is someone else better then I'm to do it (delegate it): After all task is correctly orgnized the I go though the todo list choose the one most important or most intersing 
to do. the [[*Daily%20review][delegate view]] and [[*Archive doen tasks][Archive view]] is checked while [[*Daily review][Daily review]].
** Task states
Setting tasks state by the command:

#+BEGIN_EXAMPLE
C-c C-t
#+END_EXAMPLE
Task states and the meaning:

| state      |                                     |
| TODO       | have not been planned               |
| NEXT       | In the todo list                    |
| SCHEDULED  | In schedule view                    |
| PROJECT    | bounch of tasks                     |
| DELEGATE   | delegate to someone else            |
| SUBPROJECT | bounch of tasks belong to a project |
| SOMEDAY    | Ideas don't want to do it now       |
| DONE       | done                                |
| CANCELLED  | tasks which are not need to be done |

Some special event will also triggle task states change:

+ When set a repeat task to done, it will automatic change to SCHEDULED 
+ When a NEXT in a project set to done will automatic set a next TODO task to NEXT

It is very important that I should keep my todo list clean, Idealy any task in the list doesn't require any prerequest, That's not always ture. 
If I can't do the task because I need get more information from someone else then I put this task in DELEGATE:
If I this task have to happen in special data. for example Holidays, Weekends, I SCHEDULED this task: 
If I need do something first before I can do this I will make it a [[*Organize project][Project]].
If I just don't do it now, I will put it SOMEDAY. 
* Organize a project
A project is a state for a task and it is also means a bounch of tasks that have to be done step by step. Here is a example, You want to join a party in your friend's home
And you don't know where he lives. then you need to do 3 things. 1) make a call to make sure the time and route to there. 2) task a bus 3) been there and enjoy the party.
The tasks should be like this:

#+BEGIN_EXAMPLE
 * PROJECT join party
 ** NEXT make a call
 ** TODO goto ada's home
 ** TODO enjoy the party
#+END_EXAMPLE

The main reason behind that I need a PRJECT is I want to keep my todo list clean, It always thows the task really need some attention. By using PROJECT setting, I don't need to 
see the tasks I can't take any activities right now. If I finished some task the next step will aotumatic shows. 

* Clocking
Clocking a task means to record how many time I spent on a task. This is a really good feature for org-mode. It is handy to generate a time report base on day/week/month. This kind of 
Report is really useful for daily and week review. 
** Clock a task
You can start a clock on one task by two commands :

#+BEGIN_EXAMPLE
C-c C-x C-i  #when the couser on one outline head 
I        #In agenda view 
#+END_EXAMPLE

When you set the task state to done or can stop clocking on this task by the command:

#+BEGIN_EXAMPLE
C-c C-x C-o  #when the couser on one outline head 
O        #In agenda view 
#+END_EXAMPLE

After record a time you a logbook item will be added to the tasks like this:
#+BEGIN_EXAMPLE
 ** TODO Interrupt by:liselott for:  software download reconnect
   :LOGBOOK:  
    CLOCK: [2015-03-02 må 13:14]--[2015-03-02 må 13:17] =>  0:03
   :END:      
#+END_EXAMPLE

** Handle Interuption 
It is very likely to happen that While I doing something . Someone ask me a question or to do something else. I will using the caputure command to capture a interupption. 
and switch to doing that. After finish the interupt task. I type C-c C-c to resume the clock to the one I previous working on.

** Orgnize task
I want my time report accruacy and completely. I introduce the Orgnize task. this is a special task as "default", that means if no task else is under clocking. the time will clock on this 
one. to enable this, I need a extra command called clock in:
#+BEGIN_EXAMPLE
C-z i
#+END_EXAMPLE

Every morning When I start work. I will type this command, And it will continue to record every minute of the day. 
#+BEGIN_EXAMPLE
C-z o
#+END_EXAMPLE
This is the one to close all the clock is running include the default one. this is the command I used every evening I finish all day's job.

** Ease way to find the record history
Some times I want to do the task I previously working on(most case is a meeting because the captured meeting task will not automitic resume clock to the previous one).
I can use this command:
#+BEGIN_EXAMPLE
C-u C-x C-i 
#+END_EXAMPLE
This command will echo the clock history view, I can easily find the previours clocked tasks.

* Daily review
I have a special scheduled task for daily review. It happens every weekdays. This is a drawback for org-mode that I can't set a conditional repeated task. so I have to assign five tasks 
And make all of them repeat once a week on different days. 
The main purpose for daily review is: 
+ Check the tasks status, and category, refile the tasks if needed.
+ Check the clocked time by the command:

#+BEGIN_EXAMPLE
v c #in the agenda view
#+END_EXAMPLE

+ Generate the time report.

#+BEGIN_EXAMPLE
C-c a E
#+END_EXAMPLE

+ Prepare the tasks for the next day.

* Weekly review
According to the GTD theroy weekly review is a key activity to maintain the whole system run and working. This is also a special SCHEDULED task. 
The purpose why I do weekly review is :
+ Make sure all the task is in the correct place.
+ Make sure all the thing needs my attention is in the system.
+ Make sure all the tasks in the system make some progress. 

For these purposes I have another customer agenda view called review view it is eoched by the command:
#+BEGIN_EXAMPLE
C-c a r
#+END_EXAMPLE
The advise from the personal management bible "get things done" is every week we need at least a whole afternoon to do the weekly review. It is very diffcault for me 
the have a seperate whole afternoon, but I still try to manage my self 2 hours per week to do it. 
And I realize that some hints indicate my system is clapsing. 
+ Something important suddenly comes to my mind. I can't find it.
+ I realize that some good idea I thought before but not recored.
+ Some task just stay in my todo list for 3 weeks. 
I still working on that to make this system more sensitive if this hints happens.
* Archive doen tasks
Archive tasks will remove my tasks form my org files to a org_archive file. and it will never be shown in any of my org files again. 
It is done by the command:
#+BEGIN_EXAMPLE
a y
#+END_EXAMPLE
Note that archive task not just means change the task and get rid of it. but also is a great chance to see the task again. it also a reminder 
that I need put something to my wiki system, some new knowledge new way. Almost every task I have been working hard worth some more effort to rethink 
about it and record something. I don't do it very well now and continus improve on it.
[fn:1] See[[*Clocking][ Clocking]]
[fn:2] The task while capturing will be clocked, see [[*Clocking][Clocking]]
[fn:3] The janurals are something not for any purpose such as go to toilet break and lunch this is only used for time report see [[*Clocking][Clocking]]




